### PR TITLE
bugfix: doesn't work on ItsyBitsy M0 Express without this conversion

### PR DESCRIPTION
**Pull request by fvzeppelin**
Not sure if this is relevant for all devices, but at least for mine ;)

### CODE REVIEW

**Comment by bablokb** [comment]
Hi, I will check and come back to you. Which version of CircuitPython are you using?

**Comment by fvzeppelin** [comment]
Hi, I am on 5.3.0 (latest stable)

**Comment by bablokb** [comment]
I just tried it with 5.3.0 and the trinket-m0, which  is the (almost) the same processor. Works perfectly as is. Have you tried it with `examaples/main.py`?

Looking at the python docs, bytes and bytearray only differ in a single respect: a bytearray is mutable whereas bytes are not. Otherwise they are interchangeable. I see no reason that the HD44780 modifies any bytes, and the interface chip PCF8574T shouldn't either. But you never know what hardware does.

Could you please try a simplified version of your patch:

    def _write_to_i2c(self,data):
      with self._device:
        self._device.write(bytearray([data]))
      time.sleep(0.0001)

**Comment by fvzeppelin** [comment]
Hi @bablokb, I have tried it in a slightly different setup (because I have added another device in the meantime, but not on the i2c lines). Strange thing: all three version worked:
- your proposal
- my proposal
- the original version
As I cannot reproduce the problem, I close the issue.
Thank you for supporting, anyway and sorry for wasting time!

**Pull request closed without merging**
